### ISSUE TITLE
Support subscriptions

### ISSUE THREAD

**Issue by thatneat** [graphql-python/graphene-django#120]
Subscription support was added to graphene in graphql-python/graphene#35. It would be awesome to have it built in to graphene-django so that we can build real-time apps with it!

**Comment by BossGrand** [comment]
This is being talked about here in graphene

https://github.com/graphql-python/graphene/issues/430

**Comment by eamigo86** [comment]
Hi @thatneat, please, visit this [module ](https://github.com/eamigo86/graphene-django-subscriptions) might interest you to use subscriptions on graphene-django

**Comment by mvanlonden** [comment]
Subscriptions added in v2 https://github.com/graphql-python/graphene/releases/tag/v2.0.0

**Comment by mvanlonden** [comment]
Reopening to add native support for subscriptions using channels

**Comment by firaskafri** [comment]
@eamigo86 what are your thoughts regarding adding subscriptions to the django-graphene repo?

**Comment by fkromer** [comment]
@firaskafri @eamigo86 The package [graphene-subscriptions](https://github.com/jaydenwindle/graphene-subscriptions) has great integration of GraphQL subscriptions with Django models. Probably it would be valueable to get in contact with the lead dev for possible integration as well.

**Comment by Suor** [comment]
So there is no advised way to do that?

**Comment by Eraldo** [comment]
I am also a bit hesitant to use  [graphene-subscriptions](https://github.com/jaydenwindle/graphene-subscriptions) since the last commit was nearly half a year ago.

Are subscriptions on the roadmap? Is there such a thing? 😊

**Comment by ulgens** [comment]
@jkimbo Around 3.2 or 3.3 maybe?

**Comment by ulgens** [comment]
I'm reopening the issue btw. This is a missing feature in graphene-django side, that's for certain.

**Comment by jaydenwindle** [comment]
Hi all! Author of [`graphene-subscriptions`](https://github.com/jaydenwindle/graphene-subscriptions) here 😊

It would be awesome to see subscriptions support added to `graphene-django`. I'm happy to submit a PR with my subscriptions implementation if there is interest in integrating it into this library.

One challenge with implementing subscriptions in `graphene-django` v2 right now is that you need to stitch together the `async`-based pattern that Django Channels uses with the `Observable`-based pattern used in `graphene`. This is what `graphene-subscriptions` does currently.

(Side note: @Eraldo I can definitely understand your concern there! Rest assured that I'm still actively supporting it (I'm hoping to ship `graphene-subscriptions` v2 very soon). Feel free to open an issue or DM me if you have any questions!)

Once `graphene-django` v3 ships with support for `async` resolvers, implementing built-in support for subscriptions will be much simpler and the implementation will be much cleaner.

@jkimbo I would love to help ship subscriptions support for `graphene-django` if that's something you and the team would be interested in supporting natively.

**Comment by SmileyChris** [comment]
Also, if you're looking for an alternative, I'm the author of the graphql-ws branch handling django channels 2 subscriptions. Hopefully will have that merged to master soon (but actively using the branch in a pre-production environment successfully).

Seems like there's gaining traction on multiple solutions that are getting this done. Also happy to help work on (or consult on) a built in solution if it fits.

**Comment by Eraldo** [comment]
This seems to be another option that I want to include for completion's sake: https://github.com/datadvance/DjangoChannelsGraphqlWs

**Comment by Eraldo** [comment]
Any updates? *hopeful-eyes*
Any clue which 3rd party library is more/less likely to make it into graphene-django at some point?

**Comment by Ahtii** [comment]
Anyone please help i am stuck in creating custom view (instead of GraphiQL) for subscription i am using [graphene-subscription](https://pypi.org/project/graphene-subscriptions/)  package here is the [link](https://stackoverflow.com/questions/65905656/how-to-create-custom-graphqlview-that-implements-subscriptions)  to my problem.

**Comment by Eraldo** [comment]
It has been over a year and a half since the last comment. *sigh*

**Comment by procopio420** [comment]
all available libraries that I found has a lot of dependency problem with newer graphene versions :/ and implementing it by hand is being painful

**Comment by prokher** [comment]
We just published a huge update to [DjangoChannelsGraphqlWs](https://github.com/datadvance/DjangoChannelsGraphqlWs) to support latest Django, Graphene & GraphQL-core. We still be happy to see subscriptions natively supported in Graphene & GraphQL-core, but until they are not there we stick to our own implementation, e.g. to [DjangoChannelsGraphqlWs](https://github.com/datadvance/DjangoChannelsGraphqlWs).

**Comment by adambirds** [comment]
Anybody any ideas what can be done to help get this implemented?

Looking around and all the recommended packages [here](https://docs.graphene-python.org/projects/django/en/latest/subscriptions/) have either gone years without an update or still don't support greater than Django 3.x when we're now on Django 5.x.

Along with the ability to fetch a fine-tuned amount of data unlike with rest, subscriptions are one of the main reasons behind using GraphQl for live updating of data and its a shame it hasn't been implemented in the core package or even received a single comment from a maintainer on this issue.

**Comment by patryk-matis** [comment]
Yeah, graphene django without subscriptions after so many years is a bummer
