### ISSUE TITLE
Filter by foreign key integer ID with non-relay node not working

### ISSUE THREAD

**Issue by antonkhelou** [graphql-python/graphene-django#130]
```
class Project(models.Model):
    name = models.CharField(max_length=100, unique=True)

class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)

class ProjectNode(DjangoObjectType):
    class Meta:
        model = models.Project
    id = graphene.Int()

class TaskNode(DjangoObjectType):
    class Meta:
        model = Task
        interfaces = (relay.Node,)

class TaskFilter(django_filters.FilterSet):
    class Meta:
        model = Task
        fields = {
            'name': ['exact', 'icontains'],
            'project__id': ['exact'],
        }
```

The above is the setup I have, where TaskNode is a Relay node and ProjectNode is a non-Relay node (i.e. needs to use actual IDs).

The issue is that when I do:

```
query{
  tasks (project_Id:1){
    edges {
      node {
        id
        project {
          id
          name
        }
      }
    }
  }
}
```

I get no results, but:

```
query{
  tasks{
    edges {
      node {
        id
        project {
          id
          name
        }
      }
    }
  }
}
```
Returns a all my results with the correct integer IDs of the project relations.

I decided to set the ProjectNode to use the Relay interface, i.e.:
```
class ProjectNode(DjangoObjectType):
    class Meta:
        model = models.Project
        interfaces = (relay.Node,)
```

and use one of the Relay IDs associated to a project and it returned the correct filtered results:
```
query{
  tasks (project_Id:"UHJvamVjdE5vZGU6MQ=="){
    edges {
      node {
        id
        project {
          id
          name
        }
      }
    }
  }
}

RESULT:
{
  "data": {
    "tasks": {
      "edges": [
        {
          "node": {
            "id": "VGFza05vZGU6Nw==",
            "creator": {
              "id": 1
            },
            "assignee": null,
            "project": {
              "id": "UHJvamVjdE5vZGU6MQ==",
              "name": "test"
            }
          }
        }]
    }
  }
}
```
What's interesting is that, I then reset the ProjectNode definition to the original non-Relay interface definition and decided to rerun the same query (i.e. with the Relay ID) and the correct filtered results but with the actual project integer IDs:
```
query{
  tasks (project_Id:"UHJvamVjdE5vZGU6MQ=="){
    edges {
      node {
        id
        project {
          id
          name
        }
      }
    }
  }
}

RESULTS:
{
  "data": {
    "tasks": {
      "edges": [
        {
          "node": {
            "id": "VGFza05vZGU6Nw==",
            "creator": {
              "id": 1
            },
            "assignee": null,
            "project": {
              "id": 1,
              "name": "test"
            }
          }
        }]
    }
  }
}
```

I suppose this is a non standard way of using GraphQL but I already have part of the project setup working without GraphQL and everything in that part works with integer IDs. The Task part of the project is a module where I decided to use GraphQL and the Relay spec (for the pagination benefits)

**Comment by antonkhelou** [comment]
Fixed it by modifying the Filter class:
```
class TaskFilter(django_filters.FilterSet):
    project__id = django_filters.ModelChoiceFilter(queryset=Project.objects.all().values_list('id', flat=True))

    class Meta:
        model = Task
        fields = {
            'name': ['exact', 'icontains'],
            'project__id': ['exact'],
```

**Comment by Vitiell0** [comment]
@antonkhelou I am running into the same problem. 

I tried the solution that you posted about modifying the filter class but am not getting that to work either.

I see that you closed and then re-opened this issue. Have you made any progress or is the filterset modification not working for you anymore either?

**Comment by ziXet** [comment]
@antonkhelou 's workaound worked for me but I don't understand the logic behind it.

**Comment by phalt** [comment]
Can we check this is still an issue? Issue is 2 years old and we've made some releases since then.
